### ISSUE TITLE
Reduce number of auth tokens used in unit tests

### ISSUE THREAD

**Issue by brittanylau** [RagtagOpen/freefrom-map-backend#60]

**Comment by egiurleo** [comment]
This is a good idea. A few things I can think of:
1. There should be a way to create 1 token per test run rather than 1 token per test and then re-use that token...
2. Once the backend is in a stable place, maybe we could only run tests that require auth on CI (like have an environment variable called `RUN_AUTH_TESTS` or something that's false by default) -- that way if someone specifically needs to test auth locally, they can, but they won't accidentally use a bunch of tokens.

**Comment by brittanylau** [comment]
Oops! @egiurleo I just saw your comment now – in my PR I just ended up grabbing 1 token for `TestAuth.test_private_endpoint_auth`, and the API tests mock the auth verification method (since the auth test should catch if the logic isn't working). In the end, we still get 1 token per test run. Let me know if that works!

I think #2 is a great idea as well. :)
